### ISSUE TITLE
Unexpected behaviour when using references with the results of !apply

### ISSUE THREAD

**Issue by flexthink** [speechbrain/HyperPyYAML#11]
The results of `!apply` behave differently from ordinary, fixed variables when used inside of references. It appears that what is being resolved in the reference is the arguments to !apply and not the result

Given below is a YAML example to illustrate this.

__YAML__:
```yaml
a: "a"
b: !apply:operator.add
  - "b"
  - "c"
c: !apply:lib.test
d: !ref <a>-<b>-<c>
```

__Python__:

`test.py`:

```python
from hyperpyyaml import load_hyperpyyaml

yaml = """
a: "a"
b: !apply:operator.add
  - "b"
  - "c"
c: !apply:lib.test
d: !ref <a>-<b>-<c>
"""

yaml_dict = load_hyperpyyaml(yaml)
print(yaml_dict)
```

`lib.py`:

```python
def test():
        return "test"
```

Shell:
```sh
python test.py
```

**Expected Output**:
```
{'a': 'a', 'b': 'bc', 'c': 'test', 'd': "a-bc-test"}
```
**Actual Output**:
```
{'a': 'a', 'b': 'bc', 'c': 'test', 'd': "a-['b', 'c']-"}
```

**Comment by pplantinga** [comment]
The issue here is whether `!ref` tag or `!apply` tag happens first. It was designed to have the `!ref` tag occur first.

Simple example where you might want this behavior:
```
a: 3
b: 4
c: !apply:operator.add
  - !ref <a>
  - !ref <b>
```

**Comment by pplantinga** [comment]
I think a really neat solution to this would be to build a dependency graph of all the operations and then resolve them in order.

**Comment by pplantinga** [comment]
Hi @matln would you consider making a PR with your fix for this issue?

**Comment by matln** [comment]
Hi @pplantinga, I will do it in the next few days.

**Comment by mravanelli** [comment]
@pplantinga
