### ISSUE TITLE
hyperpyyaml sometimes loads scientific e notation as string

### ISSUE THREAD

**Issue by larsrgit** [speechbrain/HyperPyYAML#12]
When calling `hparams=load_hyperpyyaml("a: 1e-6")`,  `hparams["a"]` is a string. This can be avoided by calling `hparams=load_hyperpyyaml("a: 1.0e-6")` instead. 

This would not be much of an issue, but when using operations on references in the yaml such as

```
hparams=load_hyperpyyaml(
"""
a: 0.0001
b: 10.0
c: !ref <a> / <b>
"""
)
```
which results in `hparams["c"]='1e-5'` being a string, the user has no control. Hyperpyyaml resolves the references and the devision as 1e-5 and not 1.0e-5 which results in a string and not a float.

**Comment by Gastron** [comment]
Yes, this is the same issue as discussed in #8 . See that issue for an explanation - basically it comes from the underlying PyYAML parser.

**Comment by larsrgit** [comment]
Thanks. I answered with a possible fix in the other issue and will close this one.
