### ISSUE TITLE
Overriding any value get parsed as a string

### ISSUE THREAD

**Issue by JBondi** [speechbrain/HyperPyYAML#16]
A boolean, float, int in a YAML file gets parsed as its type. But if it's overridden, it is parsed as a string.

File test.yaml
```
value_flt: 0.1234
value_int: 123
value_bool: True
```

File test.py
```
from hyperpyyaml import load_hyperpyyaml
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('yaml_file')
parser.add_argument('--overrides', nargs='+')
parsed_args, unknown = parser.parse_known_args()


params_file = parser['yaml_file']
o_iter = iter(parser.overrides)
overrides = dict(zip(o_iter, o_iter))

 with open(params_file) as test_file:
     params = load_hyperpyyaml(test_file, overrides)
     print(type(params['value_flt']))
     print(type(params['value_int']))
     print(type(params['value_bool']))
```

When run with  `$python test.py test.yaml` it produces the following output:

```
<class 'float'>
<class 'int'>
<class 'bool'>
```

But running it with overrides such as `$python test.py test.yaml --overrides value_flt '3.14' value_int 256 value_book False` I get the following:

```
<class 'str'>
<class 'str'>
<class 'str'>
```

**Comment by mravanelli** [comment]
I see, I think there should be consistency here. Any idea Peter?

**Comment by Adel-Moumen** [comment]
@pplantinga

**Comment by pplantinga** [comment]
This is actually an issue with how `argparse` is being used here, if you don't specify type, `argparse` assumes the input is a string.
